### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [yamashum/fx_traderhub#25]
MVPリリースお疲れ様でした
LGTMです！
本リリースまでのスケジュールをこのissueのコメントで返答お願いします。

以下にレビュー内容等記述いたします

### 技術選定
Rails5系を使用しているかと思いますが、[こちら](https://endoflife.date/rails)をみていただけるとわかるかと思うのですが、5系はかなり前にサポート期間が終了していますので就活時に何か突っ込まれるかもしれませんので明確な技術選定理由を用意するかアップデートすることをお勧めします。

### 技術面
また、投稿された画像が反映されていないものがあったり、アカウント削除機能でエラーが出る、Gemfileにはredisが書いてあるがredisの設定項目が見当たらない(勘違いでしたらすいません)など細かな部分で改善が必要かと思いました。
しかし、ActionCableを使ったチャット機能や通知の既読管理などにチャレンジされているところは良いかと思います。

### UI・UX面
UIは整っており何をやればいいのかわかりやすいものになっているかと思います。
しかし、FXをテーマに据えたアプリならではの特徴が薄くこれで本当にFXトレーダーの人に使ってもらえるかどうかのイメージがあまりわかなかったです。
とりあえず知り合いやTwitterなどのコミュニティのFXトレーダーの人10人くらいに使ってもらえる様なアプリになる様に改善するとよりしっかりとしたサービスになるかと思います。
実際に知り合いのFXトレーダーの人に声をかけてフィードバックをもらうなどすると良いかもしれませんね。

### 就活に向けてのアピールポイントをつくる
以下の資料を参考に就活時にアピールできる機能を作成できるとより良いかと思います
https://esa-pages.io/p/sharing/2315/posts/22496/445f4048aab0b49b4730.html

また、READMEも就活に向けてupdateしましょう

**Comment by yamashum** [comment]
お忙しい中、ご意見とアドバイスをありがとうございます。以下、アドバイス頂いた内容に対する今後の方針です。

**修正箇所**:
rails 5系とredisとREAD.mdは該当箇所を確認し、修正していきます。画像の投稿とアカウント削除の件なのですが、ローカルでは機能していたのですが、デプロイした後はうまくいかず、苦戦しており、これから改善していきます。

**追加機能**:
FXをテーマとしたアプリの特徴が出るようにすることと、LINE通知機能を作成をしていこうと思います。

本リリースは１２月１５日を予定しております。レビューありがとうございました。がんばります！
